name: Canary Release

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  canary-release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: |
          cd typescript
          npm ci
      
      - name: Build and test
        run: |
          cd typescript
          npm run build
          npm run test
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Create canary version
        run: |
          cd typescript
          # Get current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          # Create canary version with timestamp and PR number
          CANARY_VERSION="${CURRENT_VERSION}-canary.${GITHUB_PULL_REQUEST_NUMBER}.$(date +%Y%m%d%H%M%S)"
          # Update package.json
          npm version $CANARY_VERSION --no-git-tag-version
          # Add publishConfig for canary tag
          node -e "const pkg = require('./package.json'); pkg.publishConfig = { tag: 'canary' }; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2))"
      
      - name: Publish canary version
        run: |
          cd typescript
          npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Update documentation
        run: |
          cd typescript
          # Update README.md with canary installation instructions
          echo -e "\n## Canary Releases\n\nTo install the latest canary version:\n\`\`\`bash\nnpm install browserstate@canary\n\`\`\`\n\nTo install a specific canary version:\n\`\`\`bash\nnpm install browserstate@${CANARY_VERSION}\n\`\`\`\n\nCanary releases are pre-release versions that may contain breaking changes or experimental features. Use with caution in production environments." >> README.md
      
      - name: Commit and push changes
        run: |
          git add typescript/package.json typescript/README.md
          git commit -m "chore: release canary version ${CANARY_VERSION}"
          git push 