name: Python Cross-Platform Tests

on:
  push:
    branches: [ master, main ]
    paths:
      - 'python/**'
      - '.github/workflows/cross-platform-python.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'python/**'
      - '.github/workflows/cross-platform-python.yml'
  workflow_dispatch:

jobs:
  python-package:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./python
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'python/pyproject.toml'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel
          pip install -e ".[dev,redis,s3,gcs]"
      
      - name: Build package
        run: |
          python -m build
      
      - name: Basic import test
        run: |
          python -c "import browserstate; print(f'Successfully imported browserstate version {browserstate.__version__}')"
      
      - name: Run tests
        run: |
          python -m pytest tests/ -k "not integration"
      
      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-${{ matrix.os }}
          path: python/dist/*
          retention-days: 7 