name: Interoperability Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-redis-typescript:
    name: Python → Redis → TypeScript
    runs-on: ubuntu-latest
    env:
      CI: 'true'
      HEADLESS: 'true'
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'typescript/package-lock.json'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install boto3 google-cloud-storage redis playwright
          python -m pip install -e ./python
          python -m playwright install chromium --with-deps

      - name: Install TypeScript dependencies
        run: |
          cd typescript
          npm ci

      - name: Build TypeScript
        run: |
          cd typescript
          npm run build

      - name: Run cross-language test (Python → Redis → TypeScript)
        run: |
          cd tests/interop/python-redis-typescript
          npm install
          python test_cross_language.py
  
  typescript-redis-python:
    name: TypeScript → Redis → Python
    runs-on: ubuntu-latest
    env:
      CI: 'true'
      HEADLESS: 'true'
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'typescript/package-lock.json'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install boto3 google-cloud-storage redis playwright
          python -m pip install -e ./python
          python -m playwright install chromium --with-deps

      - name: Install TypeScript dependencies
        run: |
          cd typescript
          npm ci
          npm install -g playwright
          npx playwright install chromium --with-deps

      - name: Build TypeScript
        run: |
          cd typescript
          npm run build

      - name: Run cross-language test (TypeScript → Redis → Python)
        run: |
          cd tests/interop/typescript-redis-python
          npm install playwright
          node create_state.mjs
          python verify_state.py 