name: Python Tests

on:
  push:
    branches: [ master, main ]
    paths:
      - 'python/**'
      - '.github/workflows/python-tests.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'python/**'
      - '.github/workflows/python-tests.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'python/pyproject.toml'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install package with all optional dependencies
        pip install -e ".[dev,redis,s3,gcs]"
    
    - name: Run tests
      run: |
        python -m pytest tests/
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: python/pytest-results.xml
        retention-days: 7 