name: Python Dependency Isolation Tests

on:
  push:
    branches: [ master, main ]
    paths:
      - 'python/**'
      - '.github/workflows/python-dependency-isolation.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'python/**'
      - '.github/workflows/python-dependency-isolation.yml'
  workflow_dispatch:

jobs:
  test-core-import:
    runs-on: ubuntu-latest
    name: Base Import Without Dependencies
    defaults:
      run:
        working-directory: ./python

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'
        cache-dependency-path: 'python/pyproject.toml'
    
    - name: Install package without optional dependencies
      run: |
        python -m pip install --upgrade pip
        # Install only the core package without optional dependencies
        pip install -e ".[dev]"
    
    - name: Verify core modules can be imported
      run: |
        python -c "import browserstate; print('Successfully imported browserstate')"
        python -c "import browserstate.storage.local_storage; print('Successfully imported LocalStorage')"

    - name: Run lazy import tests
      run: |
        python -m pytest tests/test_lazy_imports.py -v

  test-redis-storage:
    runs-on: ubuntu-latest
    name: Test Redis Storage Only
    defaults:
      run:
        working-directory: ./python

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'
        cache-dependency-path: 'python/pyproject.toml'
    
    - name: Install with Redis only
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,redis]"
    
    - name: Test Redis storage
      run: |
        python -c "from browserstate import RedisStorage; print('Successfully imported RedisStorage')"

  test-s3-storage:
    runs-on: ubuntu-latest
    name: Test S3 Storage Only
    defaults:
      run:
        working-directory: ./python

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'
        cache-dependency-path: 'python/pyproject.toml'
    
    - name: Install with S3 only
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,s3]"
    
    - name: Test S3 storage
      run: |
        python -c "from browserstate import S3Storage; print('Successfully imported S3Storage')"

  test-gcs-storage:
    runs-on: ubuntu-latest
    name: Test GCS Storage Only
    defaults:
      run:
        working-directory: ./python

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'
        cache-dependency-path: 'python/pyproject.toml'
    
    - name: Install with GCS only
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,gcs]"
    
    - name: Test GCS storage
      run: |
        python -c "from browserstate import GCSStorage; print('Successfully imported GCSStorage')" 