name: Python Tests

on:
  push:
    branches: [ master, main, '**' ]
    paths:
      - 'python/**'
      - '.github/workflows/python-tests.yml'
  pull_request:
    branches: [ master, main, '**' ]
    paths:
      - 'python/**'
      - '.github/workflows/python-tests.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        cache-dependency-path: 'python/pyproject.toml'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install package in development mode
        pip install -e .
        # Install test dependencies
        pip install -e ".[dev]"
    
    - name: Run tests
      run: |
        python -m pytest tests/
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: python/pytest-results.xml
        retention-days: 7 