name: TypeScript Dependency Isolation Tests

on:
  push:
    branches: [ master, main ]
    paths:
      - 'typescript/**'
      - '.github/workflows/typescript-dependency-isolation.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'typescript/**'
      - '.github/workflows/typescript-dependency-isolation.yml'
  workflow_dispatch:

jobs:
  build-full-package:
    name: Build Full Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'typescript/package-lock.json'
      
      - name: Install all dependencies
        run: npm ci
      
      - name: Build package
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: typescript/dist/
          retention-days: 1

  test-local-storage:
    name: Test Local Storage Only
    runs-on: ubuntu-latest
    needs: build-full-package
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: typescript/dist/
      
      - name: Install minimal dependencies
        run: |
          npm install fs-extra
      
      - name: Test LocalStorage
        run: |
          node -e "
            const { BrowserStateManager, LocalStorage } = require('./dist');
            console.log('Successfully imported LocalStorage');
            const storage = new LocalStorage();
            console.log('Successfully created LocalStorage instance');
          "

  test-redis-storage:
    name: Test Redis Storage Only
    runs-on: ubuntu-latest
    needs: build-full-package
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: typescript/dist/
      
      - name: Install minimal dependencies
        run: |
          npm install fs-extra ioredis
      
      - name: Test RedisStorage
        run: |
          node -e "
            const { BrowserStateManager, RedisStorage } = require('./dist');
            console.log('Successfully imported RedisStorage');
            // Just test that we can create an instance without errors
            const storage = new RedisStorage({ host: 'localhost', port: 6379 });
            console.log('Successfully created RedisStorage instance');
          "
  
  test-s3-storage:
    name: Test S3 Storage Only
    runs-on: ubuntu-latest
    needs: build-full-package
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: typescript/dist/
      
      - name: Install minimal dependencies
        run: |
          npm install fs-extra @aws-sdk/client-s3 @aws-sdk/lib-storage
      
      - name: Test S3Storage
        run: |
          node -e "
            const { BrowserStateManager, S3Storage } = require('./dist');
            console.log('Successfully imported S3Storage');
            // Just test that we can create an instance without errors
            const storage = new S3Storage({ 
              region: 'us-east-1',
              bucket: 'test-bucket'
            });
            console.log('Successfully created S3Storage instance');
          "

  test-gcs-storage:
    name: Test GCS Storage Only
    runs-on: ubuntu-latest
    needs: build-full-package
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: typescript/dist/
      
      - name: Install minimal dependencies
        run: |
          npm install fs-extra @google-cloud/storage
      
      - name: Test GCSStorage
        run: |
          node -e "
            const { BrowserStateManager, GCSStorage } = require('./dist');
            console.log('Successfully imported GCSStorage');
            // Just test that we can create an instance without errors
            const storage = new GCSStorage({ 
              bucketName: 'test-bucket'
            });
            console.log('Successfully created GCSStorage instance');
          " 